# MCU name
MCU = STM32F103

BOOTLOADER = stm32duino

OPT_DEFS += -DSOFT_SERIAL_BUFFERS_SIZE=6
OPT_DEFS += -DHAL_USE_SOFT_SERIAL
OPT_DEFS += -DBUBBLE_ENABLE
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom
SRC += ../hal_soft_serial.c
